config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root :to => "home#index"
  devise_for :users
  resources :users
  resources :questions do
    resources :conditions
  end
end

app/models/condition.rb
class Condition < ActiveRecord::Base
  belongs_to :question
  validates :description, :presence => true

  scope(:not_chosen, -> do
    where({:chosen => false})
  end)

  scope(:chosen, -> do
    where({:chosen => true})
  end)
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :conditions
  validates :name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :current_password) }
  end
end

app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController
  def show
    @question = Question.find(params[:question_id])
    @condition = Condition.find(params[:id])
    redirect_to question_path(@condition.question)
  end

  def new
    @question = Question.find(params[:question_id])
    @condition = @question.conditions.new
  end

  def create
    @question = Question.find(params[:question_id])
    @condition = @question.conditions.new(condition_params)
    if @condition.save
      redirect_to question_path(@condition.question)
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:question_id])
    @condition = Condition.find(params[:id])
    render :edit
  end

  def update
    @question = Question.find(params[:question_id])
    @condition = Condition.find(params[:id])
    if @condition.update(condition_params)
      redirect_to question_path(@condition.question)
    else
      render :edit
    end
  end

  def destroy
    @condition = Condition.find(params[:id])
    question_id = params[:question_id]
    @condition.destroy
    redirect_to question_path(question_id)
  end

  private
  def condition_params
    params.require(:condition).permit(:description, :chosen)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @questions = Question.all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
    render :new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash[:notice] = "Your question was submitted successfully!"
      redirect_to "/"
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
    render :edit
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to "/"
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to "/"
  end

  private
  def question_params
    params.require(:question).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to "/"
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conditions/_form.html.erb
<%= render('layouts/errors', :object => @condition) %>

<%= form_for [@question, @condition] do |f| %>
  <%= f.check_box :chosen %>
  <br><br>
  <p><%= f.submit %></p>
<% end %>

app/views/conditions/edit.html.erb
<h3>Edit Condition</h3>

<%= render 'form' %>

app/views/conditions/edit.js.erb
$('#edit_condition').hide().after('<%= j render("form") %>')

app/views/conditions/new.html.erb
<h1>New condition for <%= @question.name %></h1>

<br>

<%= render 'form' %>

app/views/conditions/new.js.erb
$('#new_condition').hide().after('<%= j render("form") %>')

app/views/home/index.html.erb
<% if current_user %>
  <%= link_to 'New Question', new_question_path, id: "new_link", remote: true %>
  <br><br>

  <h3>Questions</h3>
  <br>

  <ul>
    <% @questions.each do |question| %>
      <li><%= link_to question.name, question_path(question) %></li>
    <% end %>
  </ul>

<% else %>

  <h2>Welcome to Would You Rather!</h2>
  <br><br>
  <h3><%= link_to "Login", new_user_session_path %> or create an <%= link_to "account", new_user_registration_path %> to begin.</h3>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Uh oh! We encountered an error. Please try again.</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to 'Profile', user_path(current_user) %></li>
        <li><%= link_to 'Logout', destroy_user_session_path, method: 'delete' %></li>
        <% else %>
        <li><%= link_to 'Login', new_user_session_path %></li>
        <li><%= link_to 'Create Account', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Would You Rather</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
    <%= render 'layouts/navbar' %>
       <div class="container-fluid">
         <div class="row">
           <p class="notice"><%= notice %></p>
           <p class="alert"><%= alert %></p>
           <%= yield %>
         </div>
       </div>

</body>
</html>

app/views/questions/_form.html.erb
<%= render "layouts/errors", :object => @question %>

<%= form_for @question do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br><br>
  <%= f.submit %>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<br>

<%= render "form" %>

app/views/questions/edit.js.erb
$('#edit_question').hide().after('<%= j render("form") %>')

app/views/questions/new.html.erb
<h1>New Question</h1>

<br>

<%= render "form" %>

app/views/questions/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>')

app/views/questions/show.html.erb
<h3><%= @question.name %></h3>
<br>

<% if @question.conditions.any? %>

<h4>You chose this.</h4>
<br>
<ul>
  <% @question.conditions.chosen.each do |condition| %>
    <li>
      <%= condition.description %>
      <% if current_user %> |
        <%= link_to "Delete", question_condition_path(@question, condition),
                                      :data => {:confirm => "Are you sure?",
                                                      :method => "delete"} %>
      <% end %>
    </li>
  <% end %>
</ul>

<br>

<h4>You decided against this.</h4>
<br>
  <ul>
    <% @question.conditions.not_chosen.each do |condition| %>
      <li>
        <%= condition.description %> |
        <%= link_to "Choose", edit_question_condition_path(@question, condition), id: "edit_condition", remote: true %>
        <% if current_user %> |
          <%= link_to "Delete", question_condition_path(@question, condition),
                                        :data => {:confirm => "Are you sure?",
                                                        :method => "delete"} %>
        <% end %>

      </li>
    <% end %>
  </ul>

<% else %>
  <p>There are no conditions yet.</p>
<% end %>

<br>

<% if current_user %>
  <p><%= link_to "Add a condition", new_question_condition_path(@question), id: "new_condition", remote: true %></p>
  <p><%= link_to "Edit", edit_question_path(@question), id: "edit_question", remote: true %></p>
  <p><%= link_to "Delete Question", question_path(@question),
                                :data => {:confirm => "Are you sure?",
                                                :method => "delete"}%></p>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h2><%= @user.email %></h2>

<br>
<%= link_to "Delete Profile", user_path(@user), :data => {:confirm => "Are you sure?", :method => "delete"}, class: "btn btn-danger btn-xs" %>